#!/bin/bash

mysql=$(dpkg-query -W -f='${Status}' mysql 2>/dev/null | grep -c "ok installed")

if [ $mysql -eq 0 ] ;
then
	echo "Pole Mysqli - Alustan installimist"
	apt-get -y install mysql-client mysql-server -y

elif [ $mysql -eq 1 ]
then
	echo "Mysql on juba olemas"
	pause
	systemctl status mysqlserver
fi
